# -----------------------------
# HTTP -> HTTPS
# -----------------------------
server {

    listen 80;

    server_name dailoff.dev www.dailoff.dev;

    # Let's Encrypt
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redireccionar todo a HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

# -----------------------------
# HTTPS
# -----------------------------
server {

    listen 443 ssl;
    http2 on;

    server_name dailoff.dev www.dailoff.dev;

    ssl_certificate /etc/letsencrypt/live/dailoff.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dailoff.dev/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;

    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:10m;

    location / {

        proxy_pass http://frontend:80;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ {

        proxy_pass http://backend:8080/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}